"use client";

import { useState } from "react";
import { BookOpen, ChevronDown, ChevronUp, Microscope, ShieldCheck } from "lucide-react";
import type { HealthExplainabilityData } from "@/store/useVitalAirStore";

interface Props {
  data: HealthExplainabilityData | null;
}

export default function HealthExplainabilityPanel({ data }: Props) {
  const [open, setOpen] = useState(true);

  if (!data) return null;

  const agentLabel = `${data.agent_name} Agent v${data.agent_version}`;

  return (
    <article className="vital-card border border-vital-border/60 p-5">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="flex w-full items-center justify-between gap-3 text-left"
        aria-expanded={open}
      >
        <span className="flex items-center gap-2 font-semibold text-vital-text">
          <Microscope className="h-5 w-5 text-vital-primary" aria-hidden />
          Health advisory — explainability
        </span>
        {open ? (
          <ChevronUp className="h-4 w-4 text-vital-muted" aria-hidden />
        ) : (
          <ChevronDown className="h-4 w-4 text-vital-muted" aria-hidden />
        )}
      </button>

      {open && (
        <div className="mt-4 space-y-5 text-sm">
          <section>
            <p className="text-xs font-medium uppercase tracking-wide text-vital-muted">
              Recommendation
            </p>
            <p className="mt-1 text-vital-text">&ldquo;{data.recommendation}&rdquo;</p>
            <p className="mt-2 text-xs text-vital-muted">
              Generated by:{" "}
              <span className="text-vital-text">{agentLabel}</span>
              {data.agent_mode ? ` (${data.agent_mode})` : ""}
            </p>
          </section>

          <section>
            <p className="flex items-center gap-1.5 text-xs font-medium uppercase tracking-wide text-vital-muted">
              <BookOpen className="h-3.5 w-3.5" aria-hidden />
              Sources used
            </p>
            <ol className="mt-2 space-y-1.5">
              {data.sources.map((src) => (
                <li key={src.index} className="flex flex-wrap gap-x-2 text-vital-text">
                  <span className="text-vital-muted">[{src.index}]</span>
                  <span>{src.title}</span>
                  <span className="text-vital-primary">— confidence: {src.confidence}%</span>
                </li>
              ))}
            </ol>
          </section>

          <section>
            <p className="text-xs font-medium uppercase tracking-wide text-vital-muted">
              Agent reasoning chain
            </p>
            <ol className="mt-2 space-y-1.5">
              {data.reasoning_chain.map((step) => (
                <li key={step.step} className="text-vital-text">
                  <span className="font-medium text-vital-primary">Step {step.step}:</span>{" "}
                  {step.description}
                </li>
              ))}
            </ol>
          </section>

          <footer className="flex flex-wrap items-center gap-2 border-t border-vital-border/40 pt-4 text-xs text-vital-muted">
            <ShieldCheck className="h-4 w-4 text-vital-primary" aria-hidden />
            <span>
              Confidence:{" "}
              <strong className="text-vital-text">{data.confidence_pct}%</strong>
              {" | "}
              Reviewed against: {data.reviewed_against.join(", ")} guidelines
            </span>
          </footer>
        </div>
      )}
    </article>
  );
}
